In [92]:
text = ["wookie stormtrooper",
        "wookie wookie wookie stormtrooper stormtrooper stormtrooper",
        "harry potter"]

In [93]:
v = [set(string.split(" ")) for string in text]

In [94]:
bagofwords = list(set([item for sublist in v for item in sublist]))

In [95]:
l = []
for line in text:
#     print(line)
    words = line.split(" ")
    print(bagofwords)
    x = []
    for word in bagofwords:
#         print(word)
        if word in words:
#             print(word)
            x.append(1)
        else:
            x.append(0)
    l.append(x)
        

['stormtrooper', 'wookie', 'harry', 'potter']
['stormtrooper', 'wookie', 'harry', 'potter']
['stormtrooper', 'wookie', 'harry', 'potter']


In [106]:
import numpy as np
word_array = np.array(l)

In [107]:
# word_array[1] = np.array([1,0,1,1])

In [108]:
def euclidean_distance(a,b):
    return np.linalg.norm(a-b)

In [109]:
import scipy.spatial.distance as sp
import scipy.stats as stats
# np.pdist

In [110]:
sp.pdist(word_array)

array([ 0.,  2.,  2.])

In [111]:
import pandas as pd
df = pd.DataFrame(word_array)

In [112]:
df

0  1  2  3
0  1  1  0  0
1  1  1  0  0
2  0  0  1  1

In [113]:
sp.pdist(word_array, 'cosine')

array([  2.22044605e-16,   1.00000000e+00,   1.00000000e+00])

In [114]:
sp.pdist(word_array, 'euclidean')

array([ 0.,  2.,  2.])

In [115]:
Y

array([ 1.73205081,  2.        ,  1.        ])

In [75]:
for 

stats.pearsonr(word_array[0],word_array[1])[0]

-0.57735026918962584

In [105]:
# np.corrcoef(word_array)

array([[ 1.        , -0.57735027, -1.        ],
       [-0.57735027,  1.        ,  0.57735027],
       [-1.        ,  0.57735027,  1.        ]])

In [85]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import pairwise_distances

vectorizer = CountVectorizer()
X = vectorizer.fit_transform(text)

In [87]:
X = vectorizer.fit_transform(text)

In [88]:
X.toarray()

array([[0, 0, 1, 1],
       [0, 0, 3, 3],
       [1, 1, 0, 0]], dtype=int64)

In [89]:
pairwise_distances(X, Y=None, metric='cosine')

array([[  2.22044605e-16,   0.00000000e+00,   1.00000000e+00],
       [  0.00000000e+00,  -2.22044605e-16,   1.00000000e+00],
       [  1.00000000e+00,   1.00000000e+00,   2.22044605e-16]])

In [90]:
pairwise_distances(X, Y=None, metric='euclidean')

array([[ 0.        ,  2.82842712,  2.        ],
       [ 2.82842712,  0.        ,  4.47213595],
       [ 2.        ,  4.47213595,  0.        ]])

In [91]:
import numpy as np
X = X.toarray()
np.corrcoef(X)

array([[ 1.,  1., -1.],
       [ 1.,  1., -1.],
       [-1., -1.,  1.]])