In [1]:
import tensorflow as tf

In [32]:
8 % 5

3

In [33]:
3 % 5

3

In [34]:
"I"*3

'III'

In [46]:
num = 4
tens = int(str(num)[-2])
tens

IndexError: string index out of range

In [64]:
romans = ["I","V","X","L","C","D","M"]  
romans[0:3]
romans[2:5]
romans[]

['X', 'L', 'C']

In [99]:
def roman(num):
    romans = [["I","V","X"],["X","L","C"],["C","D","M"],["M","√","∑"]]  
    places = len(str(num))
    roman_str = ''
    for cursor in range(places):
        roms = romans[(places-1) - cursor]
        digit = int(str(num)[cursor])
        if digit == 4:
            roman_str += roms[0]+roms[1]
        elif digit == 9:
            roman_str += roms[0]+roms[2]
        elif digit >= 5:
            roman_str += roms[1]
            roman_str += roms[0]*(digit % 5)
        elif digit < 5:
            roman_str += roms[0]*digit 
    return roman_str


# ´∂†˜µΩœ¡™£¢∞§¶•ª0º≠–Ω∑´®†¥√ß∑´®†¥¨∆˚øπ“‘æ

In [115]:
romanNumeralMap = {'M':  1000, 'CM': 900, 'D':  500, 'CD': 400, 'C':  100, 
                    'XC': 90, 'L':  50, 'XL': 40,
                   'X':  10, 'IX': 9, 'V':  5, 'IV': 4, 'I':  1}


def from_roman(roman_str):
    subset = roman_str[0:2]
    if romanNumeralMap[subset]:
        "hi"
    else romanNumeralMap[roman_str.pop(0):
    return "hi"

In [118]:
romanNumeralMap["Ms"]

KeyError: 'Ms'

In [111]:
s = "catty"
print s[0:4]
print list(s)
print list(s).pop(0)
print list(s)
# print s.pop()
# print s

catt
['c', 'a', 't', 't', 'y']
c
['c', 'a', 't', 't', 'y']


In [54]:
romans = {1:"I",5:"V"} #,10:"X",50:"L",100:"C",500:"D"}

def roman_numeral(num):
    ones = int(str(num)[-1])
    roman_str1 = ''
    ## ones place 
    if ones == 4:
        roman_str1 = "IV"
    elif ones == 9:
        roman_str1 = "IX"
    elif ones >= 5:
        roman_str1 = "V"
        roman_str1 += "I"*(ones % 5)
    elif ones < 5:
        roman_str1 = "I"*ones
    ## tens place
    roman_str10 = ''
    if len(str(num)) >= 2:
        print "hi"
        tens = int(str(num)[-2])
        print tens
        if tens == 4:
            roman_str10 = "XL"
        elif tens == 9:
            roman_str10 = "XC"
        elif tens >= 5:
            roman_str10 = "L"
            roman_str10 += "X"*(tens % 5)
        elif tens < 5:
            roman_str10 = "X"*tens
    roman_str = roman_str10 + roman_str1
    return roman_str




In [59]:
roman_numeral(99)

hi
9


'XCIX'

In [ ]:
10^(len(num)-1)
if value is "value place" less than any of the things 
in this library, then we need that library item

In [104]:

#Define digit mapping
romanNumeralMap = (('M',  1000),
                   ('CM', 900),
                   ('D',  500),
                   ('CD', 400),
                   ('C',  100),
                   ('XC', 90),
                   ('L',  50),
                   ('XL', 40),
                   ('X',  10),
                   ('IX', 9),
                   ('V',  5),
                   ('IV', 4),
                   ('I',  1))

def toRoman(n):
    result = ""
    for numeral, integer in romanNumeralMap:
        while n >= integer:
            result += numeral
            n -= integer
    return result

In [106]:
toRoman(50)

'L'

In [1]:
#http://docutils.sourceforge.net/docutils/utils/roman.py

In [7]:
sorted(set([5,1,2,3,4,3]),reverse=True)

[5, 4, 3, 2, 1]

In [143]:
def stringify(val):
    if val < 10:
        res = "0"+str(val)
    else:
        res = str(val)
    return res

monthDays = {1:31, 2:28, 3:31, 4:30, 5:31, 6:30, 7:31, 8:31, 9:30, 10:31, 11:30, 12:31}
def answer(x, y, z):
    # month/day/year
    unique_dates = sorted(set([x,y,z]),reverse=True)  
    sorted_dates = sorted([x,y,z], reverse=True)
    # print unique_dates
    # print str(x)
    if len(unique_dates) == 1:
        result = stringify(x)+"/"+stringify(y)+"/"+stringify(z) 
    elif len(unique_dates) == 2 and unique_dates[0] > 12 and sorted_dates[0] == sorted_dates[1]:
        result = stringify(unique_dates[1])+"/"+ stringify(unique_dates[0])+"/"+stringify(unique_dates[0])
    elif len(unique_dates) == 2 and unique_dates[0] > 12 and sorted_dates[0] != sorted_dates[1] and unique_dates[0] > monthDays[unique_dates[1]]:
        result = stringify(unique_dates[1])+"/"+ stringify(unique_dates[1])+"/"+str(unique_dates[0])
    elif len(unique_dates) == 3 and unique_dates[1] > 12 and unique_dates[0] > monthDays[unique_dates[2]]:            
        result = stringify(unique_dates[2])+"/"+stringify(unique_dates[1])+"/"+stringify(unique_dates[0])
    else:
        result = "Ambiguous."
    return result

In [144]:
answer(3,32,13)  # 11, 30,30 works but ll,11,30 would be ambiguous   or 1,1,99

'03/13/32'

In [150]:
# for month in range(1,13):
#     for day in range(1,monthDays[month]+1):
#         for year in range(1,100):
#             print month,day,year
#             print answer(month,day,year)
sum([1,2,3])            

6

In [230]:
import math
def answer(x):
    carts = len(x)
    bunnies = sum(x)
    greatest = math.ceil(bunnies / float(carts))
    equal_carts = int(bunnies - (bunnies % greatest))/greatest
    print sum(x)
    return equal_carts


In [235]:
answer([1,3,1,50,11,7,1,1])

75


7.0

In [172]:
14*3

42

In [244]:
sum([1,3,1,50])
ord("a")
ord("z")

122

In [274]:
letters = {"a":1,"b":2,"c":3,"d":4,"e":5,"f":6,"g":7,"h":8,"i":9,"j":10,"k":11,"l":12,"m":13,
           "n":14,"o":15,"p":16,"q":17,"r":18,"s":19,
           "t":20,"u":21,"v":22,"w":23,"x":24,"y":25,"z":26}

def answer(names):
    name_sums = [(sum([letters[letter] for letter in name]),name) for name in names]
    ordered_names = sorted(name_sums, reverse=True)
    reordered_names = [name for count, name in ordered_names]
    print ordered_names
    return reordered_names

In [276]:
names = ["hbrqz","iarry","hasry","annie","earz",]
answer(names)

[(71, 'iarry'), (71, 'hbrqz'), (71, 'hasry'), (50, 'earz'), (43, 'annie')]


['iarry', 'hbrqz', 'hasry', 'earz', 'annie']

In [264]:
def answer(names):
    name_sums = [(sum([ord(letter) for letter in name]),name) for name in names]
    ordered_names = sorted(name_sums, reverse=True)
    reordered_names = [name for count, name in ordered_names]
    print ordered_names
    return reordered_names

In [273]:
names = ["hbrqz","iarry","hasry","annie","earz"]
answer(names)

[(523, 'annie'), (434, 'earz')]


['annie', 'earz']

In [218]:
x = [24,34,23,24]
set(x)

{23, 24, 34}

In [219]:
x

[24, 34, 23, 24]

In [222]:
np.array([1,2,3])-np.array([3,2])

NameError: name 'np' is not defined

In [424]:
def answer(heights):
    if len([height for height in heights if height > 0]) < 1:
        return 0
    new_heights = [height - 1 for height in heights]
    if new_heights[0] == 0:
        new_heights = new_heights[1:len(new_heights)]
    if new_heights[len(new_heights)-1] == 0:
        new_heights = new_heights[0:-1]
    volume = len([height for ind, height in enumerate(new_heights) 
                  if height == 0 and ind != 0 and ind != len(new_heights)-1])
    print volume
    print new_heights
    return volume + answer(new_heights)

In [ ]:
mylist = [x*(x>=0) for x in mylist]

In [507]:
def answer(heights):
    # look at each slice bottom up
    volume = 0
    for stack in range(1,max(heights)):
        new_heights = [height - stack for height in heights]
        mm = [height*(height>=0) for height in new_heights]
#         print mm
        string = ''.join([str(height) for height in mm])
        print string
        layer = [int(thing) for thing in list(string.strip("0"))]
        print layer
        volume += len([height for height in layer if height == 0])
    return volume

In [2]:

def answer(heights):
    # pick peaks
    volume = 0
    flanks = [0]+heights+[0]
    peeks_filter = [True if a>=flanks[ind] and a>flanks[ind+2] else False for ind,a in enumerate(heights)]
    peeks = [(height,ind) for ind,height in enumerate(heights) if peeks_filter[ind] == True]
    troughs = [heights[vex[1]:peeks[i+1][1]+1] for i,vex in enumerate(peeks[:-1])]
    volume = sum([sum(min(trough[0],trough[len(trough)-1])-t for t in trough[1:-1] if t < min(trough[0],trough[len(trough)-1]) ) for trough in troughs])
    print( peeks)
    print( troughs)
    print( peeks_filter)
    print ([sum(min(trough[0],trough[len(trough)-1])-t for t in trough[1:-1] if t < min(trough[0],trough[len(trough)-1]) ) for trough in troughs])    
    return volume

In [ ]:
# answer([1, 2, 3, 2, 1])
answer([2, 5, 1, 3, 1, 2, 1, 7, 7, 6])

In [45]:
def peaks(heights):
    flanks = [0]+heights+[0]
    peaks = [(height,ind) for ind,height in enumerate(heights) 
             if height>=flanks[ind] and height>flanks[ind+2]]
    return peaks
#     if its more than the one to the right and left, its a potential peak. 
#     if its the first peak, it stays a peak
#     if its more or equal than the previous peak and more or equal than the next peak, its a peak
#     if its less than the previous peak but more than all subsequent peaks, its a peak
#     if its the last peak, it stays a peak

In [69]:
heights[0]

2

In [85]:
heights = [1, 4, 2, 5, 1, 2, 3] #[2, 5, 1, 3, 1, 2, 1, 7, 7, 6]
flanks = [0]+heights+[0]
nflanks = list(reversed(flanks))
right_max = [max(flanks[1:ind+2]) for ind,height in enumerate(heights)]
left_max = [max(nflanks[1:ind+2]) for ind, height in enumerate(heights)]
print(left_max)
print(right_max)
print(heights)
left_max = list(reversed(left_max))
volume = sum([min(right_max[i],left_max[i])-heights[i] for i,val in enumerate(heights)])
volume


[3, 3, 3, 5, 5, 5, 5]
[1, 4, 4, 5, 5, 5, 5]
[1, 4, 2, 5, 1, 2, 3]


5

In [95]:
def answer(heights):
    flanks = [0]+heights+[0]
    nflanks = list(reversed(flanks))
#     right_max = [max(flanks[1:ind+2]) for ind,height in enumerate(heights)]
    ### right_max
    rm = []
    rmax = 0
    for height in heights:
        if rmax < height:
            rm.append(height)
            rmax = height
        else:
            rm.append(rmax)
            
    lm = []
    lmax = 0
    for height in reversed(heights):
        if lmax < height:
            lm.append(height)
            lmax = height
        else:
            lm.append(lmax)
    lm = list(reversed(lm))
#     left_max = [max(nflanks[1:ind+2]) for ind, height in enumerate(heights)]
#     left_max = list(reversed(left_max))
    volume = sum([min(rm[i],lm[i])-heights[i] for i,val in enumerate(heights)])
    return volume

In [96]:
heights = [1, 4, 2, 5, 1, 2, 3] 
answer(heights)

5

In [94]:
left_max = [max(nflanks[1:ind+2]) for ind,height in enumerate(heights)]
left_max = list(reversed(left_max))
lm = []
lmax = 0
for height in reversed(heights):
    if lmax < height:
        lm.append(height)
        lmax = height
    else:
        lm.append(lmax)
print(list(reversed(lm)))
print(left_max)

[5, 5, 5, 5, 3, 3, 3]
[5, 5, 5, 5, 3, 3, 3]


In [87]:
answer([2, 5, 1, 3, 1, 2, 1, 7, 7, 6])

17

In [64]:
p = peaks([2, 5, 1, 3, 1, 2, 1, 7, 7, 6])
np=[]
for ind, peak in p[1:-1]:
    # if first or last peak : keep!
    # if greater than all previous peaks or greater than all future peaks : keep!
    print(peak,ind)
    print(p)
    print(p[ind+1])
    if p[ind] >= max(p[ind::]):
        np.append((peak,ind))
    if p[ind] >= max(p[0:ind+1]):
        np.append((peak,ind))
np
        

3 3
[(5, 1), (3, 3), (2, 5), (7, 8)]


IndexError: list index out of range

In [48]:
first_peak = p[0]
last_peak = p[len(p)-1]


In [34]:
def peaks(heights):
    storage = []
    flanks = [0]+heights+[0]
    print(flanks)
    # greedy evaluation
    previous_peak = 0
    peak = 0
    for i in range(1,len(flanks)-1):
        # first and last peak are kept, all 
        print(flanks[i-1],flanks[i],flanks[i+1])
        print(heights[i-1])
        if heights[i-1] > flanks[i-1] and heights[i-1] >= flanks[i+1]:
            peak = (flanks[i],i-1)
            if len(storage) == 0:
                storage.append(peak)
            else: 
                if peak >= previous_peak:
                    storage.append(previous_peak)
                    previous_peak = peak
                else: # peak is less than previous peak
                    
            
                
                
        # inbetweens must be higher or equal in 
        # height to previous 
        # or higher than the next one 
    return storage

In [35]:
peaks([2, 5, 1, 3, 1, 2, 1, 7, 7, 6])

[0, 2, 5, 1, 3, 1, 2, 1, 7, 7, 6, 0]
0 2 5
2
2 5 1
5
5 1 3
1
1 3 1
3
3 1 2
1
1 2 1
2
2 1 7
1
1 7 7
7
7 7 6
7
7 6 0
6


[(5, 1), (3, 3), (2, 5), (7, 7)]

In [670]:
(99-2)+(99-1)*3+(99-3)

487

In [566]:
ss = [(4, 1), (5, 3), (10, 5)]
ss[0][1]

1

In [426]:
answer([1, 4, 2, 5, 1, 2, 3])
0,3,1,4,0,1,2
2,0,3,-1,0,1
1,-1,2,-2,-1,0
# heights = [1, 2, 3, 2, 1]
# answer(heights)

1
[3, 1, 4, 0, 1, 2]
2
[2, 0, 3, -1, 0, 1]
0
[1, -1, 2, -2, -1]
0
[-2, 1, -3, -2]
1
[-3, 0, -4, -3]


4

In [399]:
heights = [1, 4, 2, 5, 1, 2, 3]
answer([1, 4, 2, 5, 1, 2, 3])

TypeError: object of type 'int' has no len()

In [397]:
[1,2,3]-1

TypeError: unsupported operand type(s) for -: 'list' and 'int'

In [385]:
import numpy as np
def answer(heights):
    # step 1: find peeks when previous and next number are smaller
    self = np.array([0] + heights)
    self_shift = np.array(heights + [0])
    res = (self - self_shift)#[1:len(self)] 
    res2 = self_shift - self
    cc = np.array([0] + list(res2))
    print cc
    dd = (list(res2) + [0])
    print cc > 0
    print dd 
    print res2
    # step 2: compair peeks
#     peeks = np.array(res > 0)*np.array(heights)
    # step 3: sum differences between peaks
    return  res

In [386]:
np.array([0]+[12,3])

array([ 0, 12,  3])

In [387]:
answer([1, 4, 2, 5, 4, 2, 1])

[ 0  1  3 -2  3 -1 -2 -1 -1]
[False  True  True False  True False False False False]
[1, 3, -2, 3, -1, -2, -1, -1, 0]
[ 1  3 -2  3 -1 -2 -1 -1]


array([-1, -3,  2, -3,  1,  2,  1,  1])

In [294]:
heights = [0,1, 4, 2, 5, 1, 2, 3,0]
-1,-3,2,-3,4,-1,-1,3
heights = [0,1, 0, 2, 5, 1, 2, 3,0]
-1,1,-2,-3,4,-1,-1,3

(-1, 1, -2, -3, 4, -1, -1, 3)

In [390]:
from urllib2 import urlopen
from json import load 

url = 'http://api.npr.org/query?apiKey=' 
key = 'MDAzMTA2NjkwMDEyOTc4NzIwNzYxOThmNA001'
url = url + key
url += '&numResults=50&format=json&id=1001'
url += '&requiredAssets=text'

response = urlopen(url)
json_obj = load(response)

with open('nprarticles.txt','w') as f:
    for story in json_obj['list']['story']:
        article = []
        for paragraph in story['textWithHtml']['paragraph']:
            article.append(paragraph['$text'])
        art = ' '.join(article).encode('utf-8')
        f.write(art+'\n')

In [396]:
from urllib2 import urlopen
from json import load 
import re, nltk
from nltk.stem.wordnet import WordNetLemmatizer
from nltk.corpus import wordnet, stopwords
import logging
logging.basicConfig(format='%(asctime)s : %(levelname)s : %(message)s', 
    level=logging.INFO)
from gensim import corpora, models, similarities, matutils
import numpy as np
import scipy.stats as stats
import matplotlib.pyplot as plt
 
url = 'http://api.npr.org/query?apiKey=' 
key = 'MDAzMTA2NjkwMDEyOTc4NzIwNzYxOThmNA001'
url = url + key
url += '&numResults=50&format=json&id=1001'
url += '&requiredAssets=text'
 
response = urlopen(url)
json_obj = load(response)
 
with open('nprarticles.txt','w') as f:
    for story in json_obj['list']['story']:
        article = []
        for paragraph in story['textWithHtml']['paragraph']:
            article.append(paragraph['$text'])
        art = ' '.join(article).encode('utf-8')
        f.write(art+'\n')
        
lmtzr = WordNetLemmatizer()
stops = stopwords.words('english')
html = re.compile(r'\<[^\>]*\>')
nonan = re.compile(r'[^a-zA-Z ]')
shortword = re.compile(r'\W*\b\w{1,2}\b')
copyright = 'copyright npr see visit httpwwwnprorg'
 
tag_to_type = {'J': wordnet.ADJ, 'V': wordnet.VERB, 'R': wordnet.ADV}
def get_wordnet_pos(treebank_tag):
    return tag_to_type.get(treebank_tag[:1], wordnet.NOUN)

def clean(text):
    clean_text = nonan.sub('',html.sub('',text))
    words = nltk.word_tokenize(shortword.sub('',clean_text.lower()))
    filtered_words = [w for w in words if not w in stops]
    tags = nltk.pos_tag(filtered_words)
    return ' '.join(
        lmtzr.lemmatize(word, get_wordnet_pos(tag[1]))
        for word, tag in zip(filtered_words, tags)
    )

with open('nprarticles.txt','r') as f:
    with open('corpus.txt','w') as f2:
        text = []
        for line in f:
            text.append(line)
        f2.truncate()
        for line in text:
            text = clean(line)
            f2.write(text.replace(copyright,'') +'\n')
            
def sym_kl(p,q):
    return np.sum([stats.entropy(p,q),stats.entropy(q,p)])
    
dictionary = corpora.Dictionary(line.lower().split() for 
    line in open('corpus.txt','rb'))
once_ids = [tokenid for tokenid, docfreq in 
    dictionary.dfs.iteritems() if docfreq == 1]
dictionary.filter_tokens(once_ids)
dictionary.filter_extremes(no_above=5,keep_n=100000)
dictionary.compactify()

class MyCorpus(object):
    def __iter__(self):
        for line in open('corpus.txt','r'):
            yield dictionary.doc2bow(line.lower().split())

my_corpus = MyCorpus()

l = np.array([sum(cnt for _, cnt in doc) for doc in my_corpus])
def arun(corpus,dictionary,max_topics,step=1,min_topics=1):
    kl = []
    for i in range(min_topics,max_topics,step):
        lda = models.ldamodel.LdaModel(corpus=corpus,
            id2word=dictionary,num_topics=i)
        m1 = lda.expElogbeta
        U,cm1,V = np.linalg.svd(m1)
        #Document-topic matrix
        lda_topics = lda[my_corpus]
        m2 = matutils.corpus2dense(lda_topics, lda.num_topics).transpose()
        cm2 = l.dot(m2)
        cm2 = cm2 + 0.0001
        cm2norm = np.linalg.norm(l)
        cm2 = cm2/cm2norm
        kl.append(sym_kl(cm1,cm2))
    return kl
    
kl = arun(my_corpus,dictionary,max_topics=100)

# Plot kl divergence against number of topics
plt.plot(kl)
plt.ylabel('Symmetric KL Divergence')
plt.xlabel('Number of Topics')
plt.savefig('kldiv.png', bbox_inches='tight')

In [100]:
import pandas as pd
import numpy as np

In [113]:
df = pd.DataFrame({'a':np.random.rand(100),'b':np.random.rand(100)})


In [117]:
df2 = df.drop('b', axis=1)
df2[0] = 7
df

a         b
0   0.452066  0.935207
1   0.559148  0.832862
2   0.740197  0.640188
3   0.523464  0.045727
4   0.731911  0.928052
5   0.623622  0.754590
6   0.048967  0.509885
7   0.143387  0.416344
8   0.457600  0.470559
9   0.002760  0.926286
10  0.571218  0.045990
11  0.063778  0.202298
12  0.401746  0.401773
13  0.890577  0.556049
14  0.261069  0.305082
15  0.490645  0.991351
16  0.783044  0.542866
17  0.988662  0.954138
18  0.901793  0.986649
19  0.160031  0.871194
20  0.186956  0.764613
21  0.339282  0.573777
22  0.297232  0.697594
23  0.022118  0.876315
24  0.304719  0.408914
25  0.705189  0.694384
26  0.574634  0.874750
27  0.602273  0.904118
28  0.004620  0.493432
29  0.984146  0.797076
..       ...       ...
70  0.298716  0.048179
71  0.365016  0.459241
72  0.424263  0.734150
73  0.718509  0.772552
74  0.527960  0.711704
75  0.924784  0.022154
76  0.718508  0.593956
77  0.123182  0.342852
78  0.489056  0.978878
79  0.615180  0.945692
80  0.670643  0.097427
81  0.502989  0.745361
82  0.627800  0.205544
83  0.757351  0.004251
84  0.577248  0.095033
85  0.886431  0.566839
86  0.884684  0.015514
87  0.098150  0.882700
88  0.611336  0.449215
89  0.544297  0.529499
90  0.192498  0.793076
91  0.640020  0.756718
92  0.512809  0.739856
93  0.346735  0.013217
94  0.486141  0.801001
95  0.684352  0.082831
96  0.321848  0.601397
97  0.574626  0.665142
98  0.118196  0.074753
99  0.592555  0.774344

[100 rows x 2 columns]